name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint & Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Install Rust toolchain
        run: rustup toolchain install

      - name: Install Rust toolchain components
        run: rustup component add clippy rust-analyzer rust-src

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Lint (clippy)
        run: cargo clippy --target aarch64-apple-darwin -- -D warnings

      - name: Build
        run: cargo build --release --target aarch64-apple-darwin
